language: php

dist: trusty

matrix:
    include:
        - php: 5.3
          dist: precise
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: 7.2

    fast_finish: true

before_script:
  - composer install --no-interaction -vvv
